name: founder_investor_app
description: "VERITAS - Connect founders with investors for successful fundraising and investment opportunities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  # cloud_firestore: ^5.4.0  # Temporarily disabled
  # firebase_storage: ^12.3.0  # Temporarily disabled
  
  # State Management
  provider: ^6.1.2
  
  # Authentication
  # google_sign_in: ^6.2.1  # Removed - using email/password only
  
  # UI & Notifications
  fluttertoast: ^8.2.6
  
  # Media & File Handling
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  path_provider: ^2.1.1
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # UI Components
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/